name: Building Debug app

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'



jobs:
  build_app:
    name: Building app
    runs-on: macos-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
      REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Android Debug app
        run: ./gradlew assembleDebug

      - name: Build iOS Debug app
        run: xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: androidApp/build/outputs/apk/debug/**.apk
